//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YapiApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTempCode
    {
        public long Id { get; set; }
        public string UserId { get; set; }
        public Nullable<int> ShortCode { get; set; }
        public Nullable<System.DateTime> Generated { get; set; }
        public Nullable<System.DateTime> Expires { get; set; }
        public Nullable<bool> IsUsed { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
